### ISSUE TITLE
rdata: Global declarations of read-only data of monster.cpp

### ISSUE THREAD

**Issue by mewmew** [sanctuary/notes#104]
This issue tracks the progress of documenting the global declarations of read-only data of monster.cpp.

These declarations may be inferred by cross-referencing the debug information made available from the Playstation 1 symbol files (see #1 and [sanctuary/psx](https://github.com/sanctuary/psx)) against the PC release of Diablo 1 (version 1.09b).

**Comment by mewmew** [comment]
Fixed in 6e1f715f0d2bdbea0bd92faae11b8f7b1c8e827a. The read-only data section is now fully documented.

**Comment by karlek** [comment]
Damn! Nice, job :tada:

**Comment by mewmew** [comment]
🦌
