### ISSUE TITLE
bss: Global declarations of uninitialized data of gendung.cpp

### ISSUE THREAD

**Issue by mewmew** [sanctuary/notes#198]
This issue tracks the progress of documenting the global declarations of uninitialized data of gendung.cpp.

These declarations may be inferred by cross-referencing the debug information made available from the Playstation 1 symbol files (see #1 and [sanctuary/psx](https://github.com/sanctuary/psx)) against the PC release of Diablo 1 (version 1.09b).

**Comment by sskras** [comment]
Yay! But for some reasons the progess is not 100%. It's `1968689/2048520 bytes`, right?

**Comment by mewmew** [comment]
@sskras, that's the overall progress of the uninitialized data segment (`.bss`) of `Diablo.exe`. The specific subset of the `.bss` segment associated with the `gendung.cpp` file is marked as 100% complete. Note that alignment bytes are included in these numbers.

From https://github.com/sanctuary/notes/commit/79741bf0105f7bbda15d795d27923ba2a46d2b47?diff=unified#diff-16c0e7aa6eb1209ed8f7e99b7c13c8d6R27:
```md
| [gendung.cpp](gendung.h)   | `0x52BA00`    | `0x63445F`  | ![100%](http://progressed.io/bar/100 "(1084000/1084000 bytes)") |
```
