### ISSUE TITLE
blizconv

### ISSUE THREAD

**Issue by ApertureSecurity** [sanctuary/notes#241]
Hey Mewmew, We worked on a small project some time ago and it seems like you removed it . It was called blizconv it converted images in MPQ files to the PNG format.

I thought it would be a part of this maybe. 

Do you still have this? 

PS I am sorry to make an issue to find you but I cannot get a hold of you any other way.

**Comment by mewmew** [comment]
> Hey Mewmew, We worked on a small project some time ago and it seems like you removed it . It was called blizconv it converted images in MPQ files to the PNG format.

Hi @ApertureSecurity! Glad to hear from you again :)

> I thought it would be a part of this maybe.
>
> Do you still have this?

The blizzconv project is still up and running at https://github.com/mewrnd/blizzconv

Depending on your applications, I can recommend checking out https://github.com/sanctuary/formats which is the modern reincarnation of blizzconv.

> PS I am sorry to make an issue to find you but I cannot get a hold of you any other way.

No worries at all. Wish you all the best and hope you've had a good start of the new year!

Cheers,
/u
