### ISSUE TITLE
New version of diablo on GOG

### ISSUE THREAD

**Issue by wheybags** [sanctuary/notes#255]
https://www.gog.com/game/diablo
Seems like it's been slightly edited, they ship two different copies of Diablo.exe, neither of which are the exact same as v1.09

**Comment by mewmew** [comment]
Hi Tom!

Happy to hear from you :) I'll definitely check it out.

Diablo on GoG was an instant buy!

![2019-03-08-000829_1157x1439_scrot](https://user-images.githubusercontent.com/1414531/53995219-bda2fd80-4177-11e9-80b9-b332d61a7137.png)

Cheers,
Robin

**Comment by mewmew** [comment]
Actually. I'll re-open this, so we can track specific differences between the releases in relation this this issue.

**Comment by mewmew** [comment]
@AJenbo did some initial investigation, and the executable seem to be almost identical to the 1.09 release: https://github.com/diasurgical/devilution/issues/597#issuecomment-470704457

**Comment by AJenbo** [comment]
diablo 1.09b:
468877a50658bc8ee14720efd19c626d  diabloui.dll
1d72a53cb25fc46cc13b338901cffa74  Storm.dll 266299 bytes
600283858cc830a96c641f221fdbb7a9  BATTLE.snp
efb12607816b560c114a302f7b1dc761  STANDARD.snp
0d1a2b10f8b7fc1a388109bd8abf05d1 Diablo.exe 757760 bytes

468877a50658bc8ee14720efd19c626d  diabloui.dll
8bdbaf57425660bbd0f7252cbbb3b9b2  Storm.dll 266299 bytes
600283858cc830a96c641f221fdbb7a9  BATTLE.snp
efb12607816b560c114a302f7b1dc761  STANDARD.snp
2b5cdb5e0caf5dc43c8fa6fa4d6255b5 Diablo.exe 765024 byters
gog_dx:
468877a50658bc8ee14720efd19c626d  diabloui.dlll
1ff32c283e56d8d759e25e50109450d8  Storm.dll 266299 bytes
efb12607816b560c114a302f7b1dc761  STANDARD.snp
45e2fa049b1796c6f0e62cc11568571a Diablo.exe 765024 bytes

Both MPQs are identical to the EU/Mac 1.09 version

**Comment by AJenbo** [comment]
storm.dll: GoG compared to 1.09
0x00038d54 44315c => 000000 0x00038d54

Storm.dll GoG dx compared to 1.09
0x0001867a eb => 74 0x0001867a (aka no-cd)

**Comment by mewmew** [comment]
Thanks @AJenbo for doing the analysis!!

Where all changes in `diablo.exe` of GoG and GoG dx (as compared to 1.09) done in the `.rsrc` section? Except for the two changes you mentioned already in `.text`, the one related to `reload_process` and `stop_music`.

**Comment by AJenbo** [comment]
Yes all addresses are the same.

The .rsrc changes are only present in the GoG-dx version. The GoG version's .rsrc section is unchanged. I have no idea why the exe is 7k larger then 1.09, nothing showed up when comparing the output of `objdump -xsS`.

**Comment by mewmew** [comment]
> The .rsrc changes are only present in the GoG-dx version. The GoG version's .rsrc section is unchanged. I have no idea why the exe is 7k larger then 1.09, nothing showed up when comparing the output of objdump -xsS.

You could try `vbindiff`. (I really gotta install the GoG release soon :p)

**Comment by mewmew** [comment]
They've added a digital certificate it looks like.

This is a `vbindiff` comparison of 1.09b and `GOG Games/Diablo/Diablo.exe`.

![2019-03-08-212414_965x1414_scrot](https://user-images.githubusercontent.com/1414531/54028514-90dafe80-41e8-11e9-9993-04d163385cd9.png)

**Comment by mewmew** [comment]
The only change seems to related to `Storm.dll`, and the addition of a digital certificate at the end of the `diablo.exe` binary.

As the GoG binary is (mostly) identical to the original 1.09b release, all addresses documented in the `notes` repository for the original binary are still valid for the GoG release.

Thus, closing this issue for now.
